management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8888
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false

spring:
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379





