server:
  port: 8080
  servlet:
    context-path: /search
spring:
  application:
    name: search
#  elasticsearch:
#    jest:
#      uris: http://127.0.0.1:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
#  jackson:
#    default-property-inclusion: non_null

